# Generated by Django 5.2.17 on 2026-09-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospitals.hospital'),
        ),
    ]
